### PR TITLE
Newsweek branch

### PR DESCRIPTION
**Pull request by christianotieno**

### CODE REVIEW

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @ChristianOtieno :wave: 

You have done a good job with this project so far. I like how clean and modular your code is. Please keep it up.

**However, there is a problem.** 

review-bad-path


Your paths are not well written, thus all required assets are not loaded. 
Look at this snippet of code below; the `href` is not correctly pointing to the intended asset, consider using `./src/css/style.css` instead. **Do this for the places you referenced a file/asset**. Check how the page looks using [this service](https://raw.githack.com), to make sure you fixed all or you can inspect the page to make sure you don't have a `404 Not Found error`.

https://github.com/ChristianOtieno/The-News-Week-Clone/blob/7e4dfc14c266ed8f442f56e4c36a1e0103409b23/index.html#L11-L13

**Kindly submit another code review request after fixing the issue**


Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by christianotieno** [comment]
Complied with the recommended changes, thank you Ebuka.

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @ChristianOtieno,

Great job thus far :raised_hands:, **just a few suggestions before we can merge this:**

- [x] On scrolling, the navigation bar becomes smaller and covers the width of the device but yours remains as is on a large screen. Please refer to the images below:

newsweek1
newsweek2

- [ ] The nav buttons are getting clumsy on a large screen. The navbar and main content ought to have the same width. Please refer to the images below:

newsweek3
newsweek4

- [x] The date is supposed to only display on a large screen. You still have `Tue,` showing on the left side of the navbar on smaller screens.

- [x] It doesn't contain `More stories` section.

**Kindly submit for another code review once you've fixed these issues.**

_Happy coding._ :100:

**Comment by shloch** [comment]
### Hello @ChristianOtieno 

### Great work with the corrections 👏👏
I know you must be tired ...But we're getting closer😊😊

Please take sometime and let's progress towards the end. You have some few more fixes 

**CHANGES REQUIRE**
 

- as first reviewer @ebukaume  mentioned, generate a live demo for yourself so that you can see if 
assets are loading using [https://raw.githack.com](url)
 Most of your images not showing in live demo. Dont only check the `href`, also check `src` of your **image** tags
consider using  `src="./src/assets/CULTURE/daybreak-cast-colin-ford.jpg" ` (notice the 'DOT') or `` , carry it into your CSS

**[OPTIONAL] this fix is optional**

-  if you look at the original https://www.newsweek.com/, the text is not sticking to the left/right walls. There's some small margin or space in the right and left corner. Yours lack this spacing
If you give some space, the presentation will be much better 😊
Screen Shot 2019-10-25 at 7 20 27 PM


Apart of these minor fixes, you're very good with bootstrap. Great job

Kindly submit for another code review once you've fixed these minor  issues.

Happy Coding 

-SHEY-

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @ChristianOtieno :wave: 

Good job making those changes. I understand you might be burned out already. But there are validation errors in your HTML document.

I am so sorry for missing this earlier :pray: . You can use [this service](https://validator.w3.org/nu/#textarea) to validate your HTML document. ( _Please do this for all your HTML codes in the future_ )

**Please clear the errors and submit another code review request.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by ebukaume** [comment]
## Approved! :fireworks: 

**You are now good to go :+1:  . Go and ahead and merge this branch. Congratulations :champagne:** 

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by christianotieno** [comment]
Thank for the positive reviews, Ebuka.

**Pull request merged**
